# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Portfolio Joost Ottens
# Description of the Site
description: Welcome to my portfolio website! Here you can find my latest projects and achievements.
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: joost-dev@outlook.com
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: joost-ottens
github_username:  
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 
github_username: joost2000

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Joost Ottens
# URL for the Image of the Author
author-image: ./assets/images/LinkedIn-Profile.jpg
# 60 Words About the Author
author-about: Hi! I'm Joost Ottens, I specialize in combining game development with AI, building deep learning models and creative project solutions that bring ideas to life. I enjoy creating worlds, systems, and mechanics that players can truly get lost in. Enthusiastic, solution-oriented, and a team player, I love collaborating on innovative projects. On this site, you’ll find the projects I’ve been working on, and my GitHub showcases the technical work behind them. If you’d like to reach out about a project, collaboration, or just to talk games you can find my contact details here as well.
author-url: https://github.com/joost2000

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
